name: Deploy to Render

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-24.04
    # Se ejecuta si el PR hacia main fue mergeado O si se creó un tag tipo v1.0.0
    if: github.event.pull_request.merged == true || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -f "$deploy_url"
